name: Tests
on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest, dmd-2.111.0, ldc-1.41.0]
        include:
          - os: macOS-latest
            dc: ldc-1.41.0
          - os: macOS-latest
            dc: ldc-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Try to build the lib
        run: dub build

      - name: Run tests
        run: dub test
